all: gameboy.o utilities.o main.o
	g++ -o gameboy gameboy.o utilities.o main.o -lSDL2 -lSDL2_mixer

gameboy.o:
	g++ -c src/gameboy.cpp

utilities.o:
	g++ -c src/utilities.cpp

main.o:
	g++ -c src/main.cpp

clean:
	del *.o